version: '3.9'
services:
  mongodb:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      -  ./data:/data/db
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data